version: "3.9"

services:
#  backend:
#    build:
#      context: ./backend
#      dockerfile: Dockerfile
#    ports:
#      - "8000:8000"
#    volumes:
#      - ./backend:/usr/src/app
#    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./templates/svelteUI
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./templates/svelteUI:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev -- --host
